// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatc0E_aBkhNmK5ADn1DB0QNBt_AsN874',
    appId: '1:1059789103514:web:2518641c9dba39e92f1a23',
    messagingSenderId: '1059789103514',
    projectId: 'notfication-testing-2598a',
    authDomain: 'notfication-testing-2598a.firebaseapp.com',
    storageBucket: 'notfication-testing-2598a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fVasUri1RWo0yM4IfnoI_UZLYlbl698',
    appId: '1:1059789103514:android:8fa82b59e665e6cf2f1a23',
    messagingSenderId: '1059789103514',
    projectId: 'notfication-testing-2598a',
    storageBucket: 'notfication-testing-2598a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgpHGOySd2Roz4RKJYOCKa5m6hc6GPOXE',
    appId: '1:1059789103514:ios:55c36d9852883c8a2f1a23',
    messagingSenderId: '1059789103514',
    projectId: 'notfication-testing-2598a',
    storageBucket: 'notfication-testing-2598a.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgpHGOySd2Roz4RKJYOCKa5m6hc6GPOXE',
    appId: '1:1059789103514:ios:55c36d9852883c8a2f1a23',
    messagingSenderId: '1059789103514',
    projectId: 'notfication-testing-2598a',
    storageBucket: 'notfication-testing-2598a.appspot.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCatc0E_aBkhNmK5ADn1DB0QNBt_AsN874',
    appId: '1:1059789103514:web:9393f85f5f7fadab2f1a23',
    messagingSenderId: '1059789103514',
    projectId: 'notfication-testing-2598a',
    authDomain: 'notfication-testing-2598a.firebaseapp.com',
    storageBucket: 'notfication-testing-2598a.appspot.com',
  );
}
